name: Auto Update README

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Append space to README (no newline)
        run: |
          echo "Appending space to end of file..."
          sed -i '${s/[[:space:]]*$//}' README.md
          printf " " >> README.md

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add README.md
          git commit -m "Update README.md"
          git push
